use crate::{config::{Config, ToExitCode}, conventions::conventional::builder::ConventionalFooter, package::{HOMEPAGE, NAME, VERSION}, std::panic::ExpectWithStatusCode};

pub fn get_commit_msg_footer () -> String {
  let config = Config::inject();

  ConventionalFooter::new(
    Some(
      format!("Generated by {} {} — Check it out at: {}", NAME, VERSION, HOMEPAGE)
    ),
    Some(false)
  ).try_into().expect_with_status_code(
    "Could not get conventional commit message footer",
    config.to_exit_code()
  )
}
